

apiVersion: v1
kind: Service
metadata:
  name: nginx-service2
spec:
  selector:          # service find pods using match of spec.selector.key  with  pod.labels.key
    app: nginx     
  type: LoadBalancer    
  ports:
    - protocol: TCP
      port: 80               #    listining  on 80 from usrs
      targetPort: 8080       # directing request to port 8080 of the pods having opend 8080


#  to get actual ip use :   minikube service SERVICE_NAME
