---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp
spec:
  containers:               
    - name: c01
      image: ubuntu
      command: ['bin/bash', '-c', 'echo The app is running! && sleep 3600']
  initContainers:     # this is for init container , it will run before main container
    - name: c00
      image: ubuntu
      command: ['bin/bash', '-c', 'echo The app is running init! && sleep 3600']
 